"""Added likes

Revision ID: 579ad05cb409
Revises: 0707b9916b10
Create Date: 2021-12-10 16:09:33.053896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579ad05cb409'
down_revision = '0707b9916b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster_id', sa.Integer(), nullable=True),
    sa.Column('tip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tip_id'], ['tip_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('comment', 'body',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'tip_post', 'users', ['poster_id'], ['id'])
    op.drop_column('tip_post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tip_post', sa.Column('author', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'tip_post', type_='foreignkey')
    op.alter_column('comment', 'body',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_table('like')
    # ### end Alembic commands ###
